theme: jekyll-theme-midnight
show_downloads: false
languages: ["en", "pl", "es"]
default_lang: "en"
seo:
  json_ld: false
defaults:
      lang: "en"
      title: "Mateusz Kimont - Principal Full-Stack Engineer"
      jobTitle: "Principal Full-Stack Engineer"
      fullname: "Mateusz Kimont"
      description: "Professional portfolio for Mateusz Kimont, a Principal Full-Stack Engineer with 8+ years of experience in PHP, AWS, and performance optimization. Open for new remote opportunities."
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  load_paths:
    - _sass
    - assets/css